### ISSUE TITLE
Sublime Text 3 Compatibility?

### ISSUE THREAD

**Issue by jeanpierreb** [mac2000/sublime-smart-delete#3]
Just installed this plugin via Package Control and it isn't working. I try hitting the delete key (OSX) at the end of a  line of code and it just backspaces.

Am I missing something?

**Comment by mac2000** [comment]
Checked plugin on macbook all works fine.

You should take a note that `Delete` button on macbook works like a backspace on PC, to actually delete symbols on the right you should press `Fn+Delete` then all will work as you expect.

Hope that helps

**Comment by jeanpierreb** [comment]
You're right, not sure how I missed that but it may be worth noting the difference on the README for impatient Mac users. Thanks

**Comment by jeanpierreb** [comment]
You're right, not sure how I missed that but it may be worth noting the difference on the README for impatient Mac users. Thanks

**Comment by marchenko1985** [comment]
Oh, you are totally right, added that to README, thank you for feedback

**Comment by jeanpierreb** [comment]
My pleasure Marchenko, thanks for the awesome plugin.
